### ISSUE TITLE
Login in a different domain

### ISSUE THREAD

**Issue by selamet** [skorokithakis/django-loginas#101]
My Django web app has access to 2 different domains. Processing is done according to the user's country.  When I click the button, I want to redirect a domain according to the user's country. I overrode login as a display method, but login to a different domain did not occur. When I click the button from domain a, I want to log in to domain b. How should we approach this?

**Comment by skorokithakis** [comment]
I'm afraid I don't know your exact setup, and this is out of scope for this library. I think you may have to fork the library and add some custom code, though.
