### ISSUE TITLE
The translation files don't work anymore

### ISSUE THREAD

**Issue by mavenium** [skorokithakis/django-loginas#107]
Hi,
After merging the pull request number #106 , the local directory doesn't make any more.

**Comment by skorokithakis** [comment]
Why not? What's the error? Did the PR work before merging?

**Comment by mavenium** [comment]
- I installed the `0.3.11` version from pypi.org, and everything is ok.
- If you try to install the latest version directly from GitHub the local directory doesn't make any more.
- I tried to install the latest version in a clean environment, but the local directory doesn't make any more without any error.
- You can see the result from [this address](https://i.postimg.cc/cLCjVNMq/loginas.png)
- Also, I tried to install it in the fresh Linux, but the result is the same.

**Comment by skorokithakis** [comment]
Can you post the error?

**Comment by skorokithakis** [comment]
That's because the version on the repo is still 0.3.11.

**Comment by mavenium** [comment]
I installed it from the repo, not Pypi.
I change the version to `0.3.12` in my personal repo and tried to install it, but the result is the same.

**Comment by skorokithakis** [comment]
Can you explain what the issue is? I don't understand what "the local directory doesn't make any more" means.

**Comment by mavenium** [comment]
- The locale folder is where the translation files of the project are placed.
- If you install the `django-loginas` from Pypi.org, the `0.3.11` version will be installed with the `locale` directory:
`
├── locale
│   ├── de
│   │   └── LC_MESSAGES
│   │       ├── django.mo
│   │       └── django.po
│   ├── fr
│   │   └── LC_MESSAGES
│   │       ├── django.mo
│   │       └── django.po
│   └── pl
│       └── LC_MESSAGES
│           ├── django.mo
│           └── django.po
`
- But, if you try to install the latest version from Git, this directory does not exist.
- Is it clear?

**Comment by skorokithakis** [comment]
Ah, yes, I see. Can you try to create the egg with `python3 setup.py sdist bdist` and install that?

**Comment by mavenium** [comment]
I ran the `python3 setup.py sdist bdist` command, this is a result in the `build` directory:

```
├── bdist.linux-x86_64
└── lib
    └── loginas
        ├── context_processors.py
        ├── __init__.py
        ├── settings.py
        ├── templates
        │   ├── admin
        │   │   └── auth
        │   │       └── user
        │   │           └── change_form.html
        │   └── loginas
        │       └── change_form.html
        ├── tests
        │   ├── __init__.py
        │   ├── manage.py
        │   ├── models.py
        │   ├── settings.py
        │   ├── tests.py
        │   ├── urls.py
        │   └── views.py
        ├── urls.py
        ├── utils.py
        └── views.py

9 directories, 15 files
```
The `locale` directory doesn't exist.

**Comment by skorokithakis** [comment]
Hm, try now?

**Comment by mavenium** [comment]
Thanks, It works perfectly.
