### ISSUE TITLE
Work with different frontend

### ISSUE THREAD

**Issue by mathijsfr** [skorokithakis/django-loginas#108]
Hello,

I use django as my backend and nuxt3 as my frontend. As soon as I login as another user through the admin dashboard, I get sent to the django urls. These are located at localhost:8000 for example. While my frontend is located at localhost:3000. 

How can I solve this issue? It also doesn't look like my frontend know that it's logged in as another user.

**Comment by skorokithakis** [comment]
I'm not sure how your application works, but you're redirected with a 302 to the `LOGIN_URL`. Presumably you can change that URL.
