### ISSUE TITLE
Add an audit event when loginas is used.

### ISSUE THREAD

**Issue by skorokithakis** [skorokithakis/django-loginas#33]
When loginas is used, an item should be entered into the user's "history" table, saying something like "User X logged in as user Y.".

**Comment by jacopsd** [comment]
No automatically restore the original user:
When I login as admin, then use "loginas" to become a different user without special rights.
Then log out again, the login screen is shown. I would expect to be logged in then again as admin automatically as stated in the documentation.

I tried both of these in the settings:
LOGOUT_URL = reverse_lazy('loginas-logout')
LOGOUT_URL = '/admin/logout'

Other info:
Django 1.8

Python modules in use:
Babel==2.3.4
backports-abc==0.5
BulkSMS==0.3
bumpversion==0.5.3
beautifulsoup4==4.5.3
certifi==2016.9.26
cGraph==0.1
click==6.7
coverage==4.2
diff-match-patch==20121119
dj-database-url==0.4.1
Django==1.8.16
django-ajax-selects==1.3.6
django-allauth==0.27.0
django-appconf==1.0.2
django-avatar==3.1.0
django-bootstrap-breadcrumbs==0.8.2
django-bootstrap-ui==0.4.0
django-bootstrap3==7.0.1
django-compat==1.0.13
django-crispy-forms==1.6.0
django-crudbuilder==0.2.5
django-datatable-view==0.8.3
django-datatables-view==1.13.2
django-debug-toolbar==1.5
django-debug-toolbar-template-timings==0.7
django-extensions==1.7.4
django-filter==1.0.1
django-graphos==0.3.11
django-htmlmin==0.10.0
django-import-export==0.5.1
django-inplaceedit==1.4.1
django-inplaceedit-bootstrap==0.2.1
django-inplaceedit-extra-fields==0.6.1
django-mkdocs==0.1.2
django-mysql==1.1.0
django-phonenumber-field==1.1.0
django-reversion==2.0.7
django-smuggler==0.8.0
django-super-favicon==0.6.0
django-tables2==1.2.6
django-tag-parser==2.1
django-tenant-schemas==1.6.4
django-utils==0.0.2
django.js==0.8.1
dominate==2.1.17
Faker==0.7.3
funcsigs==1.0.2
graphviz==0.5.1
gunicorn==19.6.0
ipaddress==1.0.17
Jinja2==2.9.4
livereload==2.5.1
Markdown==2.6.7
MarkupSafe==0.23
mkdocs==0.16.1
mock==2.0.0
nose==1.3.7
oauthlib==2.0.0
pbr==1.10.0
phonenumbers==8.0.1
phonenumberslite==7.7.2
Pillow==3.4.2
psycopg2==2.6.2
pydot2==1.0.33
pygraphviz==1.3.1
pyparsing==2.1.10
python-dateutil==2.6.0
python-openid==2.2.5
python-slugify==1.2.1
pytz==2016.7
PyYAML==3.12
requests==2.13.0
requests-oauthlib==0.6.2
singledispatch==3.4.0.3
six==1.10.0
slugify==0.0.1
sparkpost==1.3.5
sqlparse==0.2.1
tablib==0.11.2
tornado==4.4.2
Unidecode==0.4.19
whitenoise==3.2.2
yolk==0.4.3
django-longerusernameandemail==0.5.7
django-loginas==0.3.1
django-countries==4.5

**Comment by lggwettmann** [comment]
Great idea with the audit event. A template tag would be useful, too. So one can see when loginas was used on specific pages.

**Comment by lggwettmann** [comment]
I can try and submit for the feature I suggested. I don't know how to add audit events, I'm afraid. Let me know if you're open for that.
