### ISSUE TITLE
loginas for non staff user

### ISSUE THREAD

**Issue by jacopsd** [skorokithakis/django-loginas#60]
Question:
Is it possible to grant "loginas" rights to somebody who is not staff member?
If yes, then how would this person access the loginas feature since this button is only present in the admin pages?
-> Is there a way such a button can be placed on any page?

Thank you
Davy

**Comment by skorokithakis** [comment]
Hmm, yes, in theory you could specify `CAN_LOGIN_AS = True` and redirect users to something like `/admin/login/user/30`, but that sounds odd, what's your use case?

**Comment by jacopsd** [comment]
Use case:
My application has a user level with elevated rights (kind of application admin), where I want to grant these application admins the right to login as other users.
But these application admins do not have global django admin rights.

I tried your suggestion as follows:
    CAN_LOGIN_AS = lambda: True

Then /admin/login/user/<some user id>, but get: 
    [15/Jun/2017 08:35:44] "GET /admin/login/user/156/ HTTP/1.1" 405 0
    [15/Jun/2017 08:35:44] WARNING [django.request:41] Method Not Allowed (GET):  /admin/login/user/156/

**Comment by skorokithakis** [comment]
Ah yes, sorry, it needs to be a POST, so you need to have a form submit to that URL...

**Comment by jacopsd** [comment]
OK works fine now.
Thank you
