### ISSUE TITLE
Django admin is quoting models CharField id with special characters

### ISSUE THREAD

**Issue by cypreess** [skorokithakis/django-loginas#62]
Hi,

I found very esoteric bug. I am using custom `id` fields format for my models in django. It is CharField and values are in form of "usr_12345".  Apparently for such specific id django admin assumes that some values can brake admins urls, so they are using special layer of custom quote/unquote from here:

https://github.com/django/django/blob/master/django/contrib/admin/utils.py#L63

Basically for such id `usr_12345` django actually generate links like this: `/admin/accounts/user/usr_5F12345/change/`.

This affects also 3rd party tools as django-loginas link generated inside django admin is of this form:
`/admin/login/user/usr_5F12345/

Ths obviously creates 404 error as loginas cannot find user with quoted id `usr_5F12345`.

I am providing very easy fix for that, just unquoting the user_id value before processing. 

PS. Quoting issue is completely transparent for integer based IDs.

**Comment by skorokithakis** [comment]
Ah, great, thank you very much! I'll review later today, thanks again.

**Comment by skorokithakis** [comment]
Merged and released as 0.3.3, thank you.
