### ISSUE TITLE
Only admin can login with other user credentials? 

### ISSUE THREAD

**Issue by Allan-Nava** [skorokithakis/django-loginas#67]
Hi,

I need a feature like Netflix users management, that one users can impersonate the "children"

Thanks for support!

**Comment by skorokithakis** [comment]
Pull requests welcome!

**Comment by Allan-Nava** [comment]
If I add this feature

**Comment by skorokithakis** [comment]
What is the feature exactly?

**Comment by Allan-Nava** [comment]
Is possibile to manage the users inside the main user?

Such as the netflix feature where there is a only 1 one account that can handle and manage the 4 "childrens"

**Comment by skorokithakis** [comment]
Oh, I see what you mean now. No, I'm afraid this is not the goal of this library. This is only meant to let admins log in as users.

**Comment by Allan-Nava** [comment]
Ok, thanks btw
