### ISSUE TITLE
loginas doesn't work if the authentication backend doesn't have `get_user` method

### ISSUE THREAD

**Issue by bbirand** [skorokithakis/django-loginas#68]
`django-loginas` does not work with `django-rules` as an Authentication Backend.

We use [django-rules](https://github.com/dfunckt/django-rules) to specify custom authentication rules. As a result, we have this in our `settings`:

```
AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)
```

However, `rules.permissions.ObjectPermissionBackend` does not specify a `get_user` method (as seen [here](https://github.com/dfunckt/django-rules/blob/master/rules/permissions.py)). Even though, the Django documentation [says](https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#writing-an-authentication-backend) that each backend must implement a `get_user` method, apparently this is not enforced (!?). This was discussed in a `django-rules` issue here:
https://github.com/dfunckt/django-rules/issues/46

The reason why I believe this is not enforced is because they made some changes in the behavior of `force_login` (https://code.djangoproject.com/ticket/27542#ticket).

A quick workaround would be to check if the authentication backend has a `get_user` method. If not, then `continue`.

Does this make sense?

**Comment by skorokithakis** [comment]
Hmm, you mean as in "fail if the backend has no get_user method"? I would rather show an error message somewhere or raise an exception detailing this, but I generally agree. Since Django mandates that a `get_user` method must exist, it's the backend's problem if it doesn't implement one, although we should show a useful error message.

**Comment by bbirand** [comment]
Well, I don't think it should fail, since clearly it's OK for backends not to have a `get_user` method. My thinking was for `loginas` to continue looking for a backend that does have the method.

I created a PR here:
https://github.com/skorokithakis/django-loginas/pull/69

**Comment by bbirand** [comment]
To your point, I think it's the documentation that is wrong. Django *does* allow backends not to have a `get_user` method, because they implemented this check themselves:

https://github.com/django/django/blob/master/django/test/client.py#L592

**Comment by skorokithakis** [comment]
Hmm, that's interesting. Yes, in that case, you are correct. However, what happens if there's no suitable backend? Currently we'll fail without an error. Should we raise an exception instead?

**Comment by bbirand** [comment]
Good point. I feel like if there's not suitable backend, Django would have complained at some earlier point. They have a type of check here:

https://github.com/django/django/blob/4a461d49c775331ed52418f007974d61be1e06b9/django/contrib/auth/__init__.py#L29

**Comment by bbirand** [comment]
Or maybe it's also OK to throw an `ImproperlyConfigured` exception in loginas, as well, for good measure?

**Comment by skorokithakis** [comment]
Yeah, because that check won't fail if, for example, there's one backend that has no `get_user`, but we'll fail on ours.

**Comment by bbirand** [comment]
Updated the PR. It now raises an `ImproperlyConfigured` exception if no suitable backend is found (i.e., if there is no backend that has a `get_user` method).

**Comment by skorokithakis** [comment]
Thank you!

**Comment by bbirand** [comment]
Perfect, thanks for merging this so quickly!

**Comment by bbirand** [comment]
And when can we expect this to hit PyPI...? :)

**Comment by skorokithakis** [comment]
I'd like to test it a bit first :/ If you run master and test it for a few days to see that nothing goes wrong, let me know and I'll release. I'll do the same.

**Comment by bbirand** [comment]
Yes, sounds fair! I'll let you know if something breaks.
