### ISSUE TITLE
Please update the Changelog

### ISSUE THREAD

**Issue by manelclos** [skorokithakis/django-loginas#79]
We get notifications about new releases but don't know where to look for the changes.

**Comment by skorokithakis** [comment]
I haven't managed to find a solution that will easily generate changelogs and releases, do you know of any?

**Comment by skorokithakis** [comment]
I've posted the changelog and will probably write my own utility to automate releases, thanks.

**Comment by manelclos** [comment]
Hi @skorokithakis, I understand this involves extra time, but I much prefer changelogs that are written manually and explain what really has changed, not just a compilation of commit messages. That said, if commit messages or issue titles are well written you get close to it: https://github.com/django-import-export/django-import-export/blob/master/docs/changelog.rst

**Comment by skorokithakis** [comment]
That looks good, do you know how they do it? I'm afraid doing it manually is next to impossible as I maintain tens of OSS projects and the release cycles of some are years, so I prefer to write commit messages that will look good in a changelog. I've only found `python-semantic-release` to do that so far, and even that isn't working very well.

**Comment by manelclos** [comment]
Just asked, it is a manual process. Then he uses zest.releaser locally, it would update doc, tag, publish, upload.

**Comment by skorokithakis** [comment]
I'm going to reconfigure my changelog process to be automatic. I realize I don't actually need to use GitHub releases for the changelog, I think the CHANGELOG file is enough (and more standard), so that's easier for everyone.
