### ISSUE TITLE
AdminSite.final_catch_all_view introduced in Django 3.2 might break admin loginas button

### ISSUE THREAD

**Issue by adamyala** [skorokithakis/django-loginas#94]
Hi there,

First and foremost, thank you for a wonderful django module. It has saved countless support and QA hours.

Python version: 3.7

Django version: 3.2.2

Loginas version: 0.3.9

Django 3.2 introduced `final_catch_all_view` on the `AdminSite` class. This was introduced to prevent a bad actor from enumerating admin pages. 
https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#django.contrib.admin.AdminSite.final_catch_all_view

I think this change might have broken the admin loginas button implementation. If `final_catch_all_view` is set to True (the default), then clicking the loginas button results in a 404. If the setting is set to False, the button works as expected.

I have some custom admin urls in my project and the work around was modifying the `def get_urls()` method on `AdminSite` like so:

```python
def get_urls(self):
    url_list = super().get_urls()

    # from django.urls import path
    custom_path_obj = path(...)
    url_list = [custom_path_obj] + url_list
    # the above line used to be: url_list.append(custom_path_obj)

    return url_list
```

This is done because the `final_catch_all_view` url is added to the END of the admin url list. By prepending the custom url, we ensure the django admin finds it before the catch all. Here is a conversation in the django developers google group with more details 
https://groups.google.com/g/django-developers/c/vHZ8F8Nvq9M?pli=1

Although I think I understand how to fix this for my own admin pages, I'm unsure how to use this to fix the issue with loginas. We use loginas and would like to upgrade to 3.2, so I'm happy to take a pass at a pull request if someone else can provide some advice on how to implement.

**Comment by skorokithakis** [comment]
Thanks for the detailed bug report! A pull request would definitely be appreciated, but I don't understand why the catch-all view breaks things. Since it's added to the end, the loginas view should come before it, no?

**Comment by skorokithakis** [comment]
Oh, is the issue that the admin view now has a catch-all route, and the loginas route is in the next top-level config? If so, wouldn't an easier workaround/fix be to add the loginas top-level URL route before the built-in admin one?

**Comment by adamyala** [comment]
> If so, wouldn't an easier workaround/fix be to add the loginas top-level URL route before the built-in admin one?

That fixes it! Thank you for the simple solution. I'm a little disappointed I missed it 😅
Hopefully this ticket helps someone else in the future.

Thank you for the quick response!
